"""
SYJ OpenTrade Logic - FastAPI integration tests
==================================================
Uses FastAPI's own TestClient (built on httpx), the standard way to test
FastAPI apps. Run on your machine after `pip install -r server_fastapi/requirements.txt`
(TestClient needs httpx, add it if not already pulled in as a fastapi extra):

    pip install httpx --break-system-packages   # if not already present
    python3 -m pytest server_fastapi/test_main.py -v
    # or, if pytest isn't installed:
    python3 -m unittest server_fastapi.test_main -v
"""

import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


class TestFastAPIApp(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Termux's system /tmp is often read-only for regular processes --
        # create the temp test DB inside the project directory instead.
        local_tmp_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".test_tmp")
        os.makedirs(local_tmp_dir, exist_ok=True)
        cls.tmp_db_fd, cls.tmp_db_path = tempfile.mkstemp(suffix=".db", dir=local_tmp_dir)
        os.close(cls.tmp_db_fd)
        os.remove(cls.tmp_db_path)
        os.environ["SYJ_DATABASE_URL"] = f"sqlite:///{cls.tmp_db_path}"

        # This test file should be deterministic regardless of whatever real
        # HTS dataset (data/hts_full.json) happens to exist on this machine --
        # explicitly point at the small demo dataset so hardcoded assertions
        # below stay stable and this test's purpose (API mechanics, not HTS
        # classification accuracy) stays decoupled from live data. Must be
        # set BEFORE importing server_fastapi.main, since it loads the engine
        # once at import time.
        sample_data_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "hts_sample.json"
        )
        os.environ["SYJ_HTS_DATA_PATH"] = sample_data_path

        from fastapi.testclient import TestClient
        from server_fastapi.database import init_db
        from server_fastapi.main import app

        init_db()  # explicit -- don't rely on TestClient triggering @app.on_event("startup")
        cls.client = TestClient(app)

    @classmethod
    def tearDownClass(cls):
        if os.path.exists(cls.tmp_db_path):
            os.remove(cls.tmp_db_path)

    def test_health(self):
        resp = self.client.get("/health")
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()["status"], "ok")

    def test_classify_creates_record(self):
        resp = self.client.post("/classify", json={"description": "cordless electric drill"})
        self.assertEqual(resp.status_code, 201)
        body = resp.json()
        self.assertEqual(body["final_code"], "8467.21")
        self.assertIn("id", body)

    def test_classify_missing_description_is_422(self):
        resp = self.client.post("/classify", json={})
        self.assertEqual(resp.status_code, 422)  # FastAPI/Pydantic validation error

    def test_get_and_list_and_delete_roundtrip(self):
        created = self.client.post("/classify", json={"description": "android smartphone"}).json()
        record_id = created["id"]

        fetched = self.client.get(f"/classifications/{record_id}")
        self.assertEqual(fetched.status_code, 200)
        self.assertEqual(fetched.json()["final_code"], "8517.13")

        listed = self.client.get("/classifications?limit=100")
        self.assertEqual(listed.status_code, 200)
        self.assertTrue(any(r["id"] == record_id for r in listed.json()["results"]))

        deleted = self.client.delete(f"/classifications/{record_id}")
        self.assertEqual(deleted.status_code, 200)

        missing = self.client.get(f"/classifications/{record_id}")
        self.assertEqual(missing.status_code, 404)

    def test_openapi_docs_are_autogenerated(self):
        resp = self.client.get("/openapi.json")
        self.assertEqual(resp.status_code, 200)
        self.assertIn("/classify", resp.json()["paths"])


if __name__ == "__main__":
    unittest.main()
